apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
   - name: mysql
     image: mysql:5
     env:
      # use secrets in production
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: fleetman
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  #This service routes traffic to pods with the label app=mysql
  #The service becomes a network endpoint for either internal(other services) or external access (eg browser)
  selector:
    app: mysql
  ports:
    - port: 3306
  type: ClusterIP